// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ani-kratos-layout-layout0/internal/biz"
	"ani-kratos-layout-layout0/internal/conf"
	"ani-kratos-layout-layout0/internal/data"
	"ani-kratos-layout-layout0/internal/server"
	"ani-kratos-layout-layout0/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService)
	httpServer := server.NewHTTPServer(confServer, todoService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
